// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGGUQQvz0EILoYzAabDZjNjFzUqdMIxDc',
    appId: '1:7438395273:web:2fc76e66dd595209b62358',
    messagingSenderId: '7438395273',
    projectId: 'childmonitoring-ae6b5',
    authDomain: 'childmonitoring-ae6b5.firebaseapp.com',
    storageBucket: 'childmonitoring-ae6b5.firebasestorage.app',
    measurementId: 'G-HL3WMXSSQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoD_i8x49XieqvliGoaewg46hKFgfkaYg',
    appId: '1:7438395273:android:12542b51b61686c9b62358',
    messagingSenderId: '7438395273',
    projectId: 'childmonitoring-ae6b5',
    storageBucket: 'childmonitoring-ae6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVspJgbGOw_Scfx9jZ9u-b4EeOKGQAtzw',
    appId: '1:7438395273:ios:34c84306483a048bb62358',
    messagingSenderId: '7438395273',
    projectId: 'childmonitoring-ae6b5',
    storageBucket: 'childmonitoring-ae6b5.firebasestorage.app',
    iosBundleId: 'com.example.childMoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVspJgbGOw_Scfx9jZ9u-b4EeOKGQAtzw',
    appId: '1:7438395273:ios:34c84306483a048bb62358',
    messagingSenderId: '7438395273',
    projectId: 'childmonitoring-ae6b5',
    storageBucket: 'childmonitoring-ae6b5.firebasestorage.app',
    iosBundleId: 'com.example.childMoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGGUQQvz0EILoYzAabDZjNjFzUqdMIxDc',
    appId: '1:7438395273:web:757c5698f71c5607b62358',
    messagingSenderId: '7438395273',
    projectId: 'childmonitoring-ae6b5',
    authDomain: 'childmonitoring-ae6b5.firebaseapp.com',
    storageBucket: 'childmonitoring-ae6b5.firebasestorage.app',
    measurementId: 'G-F73895L5J0',
  );
}
